---

# HAProxy Global settings
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_extra_global_vars: []

# HAProxy Stats configuration
haproxy_enable_stats: true
haproxy_stats_port: 9000
haproxy_stats_username: "admin"
haproxy_stats_password: "aokohs9U"

# HAProxy Frontend settings
haproxy_frontends:
- name: default-fe
  binds:
  - "*:80"
  default_backend: app

# HAProxy Backend settings
# haproxy_backends:
# - name: app
#   balance: roundrobin
#   servers:
#   - name: app1
#     address: "192.168.30.185:80"
#     opts: check cookie app1
#   - name: app2
#     address: "192.168.30.191:80"
#     opts: check cookie app2
haproxy_backends:
- name: app
  balance: roundrobin
  servers:
  - name: ERC_APP4
    address: "10.0.17.84:80"
    opts: check cookie ERC_APP4
  - name: ERC_APP5
    address: "10.0.17.85:80"
    opts: check cookie ERC_APP5
  - name: ERC_APP6
    address: "10.0.17.86:80"
    opts: check cookie ERC_APP6


# Keepalived configuration
haproxy_enable_ha: true
haproxy_keepalived_bind_interface: "ens256"
haproxy_keepalived_vip: "10.0.17.11"
haproxy_keepalived_vrrp_name: "VI_1"
haproxy_keepalived_instance_state: "MASTER" # Could be ("MASTER"|"BACKUP"|"FAULT").
haproxy_keepalived_instance_priority: 200   # Must be lower that the priority value of the master instance.
