---

# - name: Set hostname
#   become: true
#   hostname:
#     name={{ inventory_hostname }}

# - name: Ensure hostname set
#   hostname: name={{ inventory_hostname }}
#   when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')
#
# - name: Ensure hostname is in /etc/hosts
#   lineinfile:
#     dest=/etc/hosts
#     regexp="^{{ ansible_default_ipv4.address }}.+$"
# line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

- name: Set hostname
  # become: True
  shell: hostnamectl set-hostname {{ sethostname }}
