---

- name: Ensure HAProxy is installed
  yum:
    name: haproxy
    state: latest
  #when: ansible_os_family == 'RedHat'

- name: Ensure Keepalived is installed
  yum:
    name: keepalived
    state: latest
  when: haproxy_enable_ha|bool
