---

- name: Install 1c-postgres
  # become: ture
  yum:
    name:
      - postgresql-1c
      - postgresql-1c-server
      - postgresql-1c-plpython
    state: latest
  tags: install_postgresql

- name: Install dependencies for the Ansible module
  # become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - python-psycopg2
  tags: install_postgresql
